### ISSUE TITLE
origin/undefined

### ISSUE THREAD

**Issue by darklight147** [mlarhrouch/azure-pipeline-gpt-pr-review#15]
TargetBranch seems to always be undefined

```
error]fatal: ambiguous argument 'origin/undefined': unknown revision or path not in the working tree
```

**Comment by mlarhrouch** [comment]
@darklight147  this issue was fixed in this issue #9, let me know if you still get the error using the latest version

**Comment by darklight147** [comment]
I did try to implement a similar approach to the function `getTargetBranchName` but unfortunalty it appears both the variables:

- System.PullRequest.TargetBranchName
- System.PullRequest.TargetBranch

are undefined

i did try using a function that the library provides:

```ts
tl.getVariables()
```

with vain, as none of the variables i got back have the a value of the target branch

**Comment by mlarhrouch** [comment]
@darklight147 can you provide more informations on how to reproduce the error, i tested the extension using OpenAI Api and Azure OpenAI service, in both case i didn't get the error of target branch

**Comment by parshutinyaroslav** [comment]
@mlarhrouch 
I got this type of error when my PR contains files that are going to delete. 

##[error]Error: fatal: ambiguous argument 'SomeFilePath/FileNamecs': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
