### ISSUE TITLE
Azure DevOps task fails with error invalid json response body

### ISSUE THREAD

**Issue by manuelsujith** [mlarhrouch/azure-pipeline-gpt-pr-review#18]
I was trying to integrate this in our Azure DevOps pipeline and it gives out an error like this below. Does this run any bell to you? I have followed the instructions from the websites.

Starting: GPTPullRequestReview
==============================================================================
Task         : Review PullRequest by GPT
Description  : This task use OpenAi GPT model to review PullRequests
Version      : 0.9.18
Author       : Mustapha Larhrouch
Help         : [More Information](https://github.com/mlarhrouch/azure-pipeline-gpt-pr-review)
==============================================================================
Changed Files (excluding binary files) : 
 Pipeline.Edge-Infra.CI.yaml
Source/DicomHub.Edge.SecretProvider/Secret/SecretGenerator.cs
Start deleting existing comments added by the previous Job ...
Existing comments deleted.
Start reviewing Pipeline.Edge-Infra.CI.yaml ...
invalid json response body at https://tpdicomhub.openai.azure.com/openai/deployments/code-davinci-002/completions?api-version=2022-12-01 reason: Unexpected token U in JSON at position 0
Start reviewing Source/DicomHub.Edge.SecretProvider/Secret/SecretGenerator.cs ...
invalid json response body at https://tpdicomhub.openai.azure.com/openai/deployments/code-davinci-002/completions?api-version=2022-12-01 reason: Unexpected token U in JSON at position 0
Finishing: GPTPullRequestReview

**Comment by mlarhrouch** [comment]
@manuelsujith are you sure that the endpoint is correct, opening it get 404 

<img width="461" alt="image" src="https://github.com/mlarhrouch/azure-pipeline-gpt-pr-review/assets/12035600/08d706a6-67ab-44d7-9127-f145be843981">

**Comment by manuelsujith** [comment]
yes. end point is correct. I took this directly from the azure AI studio portal

**Comment by mlarhrouch** [comment]
@manuelsujith your url is missing the "/chat/completions"

**Comment by mlarhrouch** [comment]
@manuelsujith  your url is missing the "/chat/completions"

**Comment by manuelsujith** [comment]
thank you so much. somehow I blindly relied on the endpoint from azure portal

**Comment by armandvanderwalt** [comment]
We are experiencing the same thing, where you able to resolve this @manuelsujith
