### ISSUE TITLE
Could you change davinci to gpt35-turbo

### ISSUE THREAD

**Issue by bellstar** [mlarhrouch/azure-pipeline-gpt-pr-review#27]
I want to request support for the gpt35-turbo model because the "text-davinci-003" model cannot be created from July 6 on Azure OpenAI Service.  
<https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/legacy-models>

**Comment by mlarhrouch** [comment]
@bellstar if you use Azure OpenAI Service you can use any model you want : https://{XXXXXXXX}.openai.azure.com/openai/deployments/{MODEL_NAME}/chat/completions?api-version={API_VERSION}

**Comment by bellstar** [comment]
@mlarhrouch,

Thanks reply for me.
I mistook the code for OpenAI in the link below as code for AOAI. I have resolved it and will close it.
<https://github.com/mlarhrouch/azure-pipeline-gpt-pr-review/blob/1db7cfa7a1d56f0a58aa4580caace063610b158a/GPTPullRequestReview/src/review.ts#L32>
