### ISSUE TITLE
 terminal prompts disabled

### ISSUE THREAD

**Issue by sarthakgupta005** [mlarhrouch/azure-pipeline-gpt-pr-review#36]
After Prompt not defined issue fixed I am now facing other issue related to "##[error]fatal: could not read Password for '[https://RadiometerGIT@dev.azure.com'](https://XXXXXX@dev.azure.com%27/): terminal prompts disabled"

![image](https://github.com/mlarhrouch/azure-pipeline-gpt-pr-review/assets/38211362/bebfef42-4c74-4646-ad53-9532678ddb40)

**Comment by gbarrs-at-em** [comment]
@sarthakgupta005 , how did you fix this problem?  I'm seeing the same thing.

**Comment by dbwodlf3** [comment]
me too. how solved??? ;(

**Comment by sarthakgupta005** [comment]
![IMG_4595](https://github.com/mlarhrouch/azure-pipeline-gpt-pr-review/assets/38211362/78693afc-a5e5-477d-ac0a-b0ed0d336231)


Add this to your code @dbwodlf3 @gbarrs-at-em

**Comment by dbwodlf3** [comment]
Wow So fast. Thanks good man. it works well!!
