### ISSUE TITLE
Can the token be set to 4096?

### ISSUE THREAD

**Issue by mlarhrouch** [mlarhrouch/azure-pipeline-gpt-pr-review#4]
Can the token be set to 4096?
https://github.com/mlarhrouch/azure-pipeline-gpt-pr-review/blob/main/GPTPullRequestReview/review.ts#L86
https://platform.openai.com/docs/guides/chat/managing-tokens

_Originally posted by @ChengYen-Tang in https://github.com/mlarhrouch/azure-pipeline-gpt-pr-review/issues/1#issuecomment-1491673498_

**Comment by mlarhrouch** [comment]
![image](https://user-images.githubusercontent.com/12035600/229756269-86bf1ee0-e2ad-40cd-bd03-8c09d983dded.png)

the max_tokens parameter is specify the max tokens that can ChatGPT use when answering, and the count tokens from our propmpt + tokens from ChatGPT shouldn't exeeded 4096.

**Comment by ChengYen-Tang** [comment]
OK, thanks

**Comment by ChengYen-Tang** [comment]
![image](https://user-images.githubusercontent.com/32535494/230291417-86671a65-990e-4c49-99a0-ad8517b1e1c5.png)
![image](https://user-images.githubusercontent.com/32535494/230291464-cd94546b-e995-436f-8c20-e4e3967961cb.png)
