### ISSUE TITLE
Error on med sized PR's

### ISSUE THREAD

**Issue by prodigz** [mlarhrouch/azure-pipeline-gpt-pr-review#5]
When using it to review a med sized PR it threw this error.

json result: {"error":{"message":"This model's maximum context length is 4097 tokens. However, you requested 4788 tokens (2788 in the messages, 2000 in the completion). Please reduce the length of the messages or completion.","type":"invalid_request_error","param":"messages","code":"context_length_exceeded"}}

The documentation from OpenAI mentions that these are hard set sizes and you would need to batch them to get them though.  Would it be possible to batch request over a certain size?

**Comment by mlarhrouch** [comment]
we reduced the max tokens of completion from 2000 to 500, so from now we can use 3597 tokens when review the PRs
