### ISSUE TITLE
Is it possible to use GPT 4 version to do the code review?

### ISSUE THREAD

**Issue by kanvishok** [mlarhrouch/azure-pipeline-gpt-pr-review#7]
How can i use gpt-4-0314? could you please add the input option for adding model?

**Comment by shailesh** [comment]
with [this](https://github.com/mlarhrouch/azure-pipeline-gpt-pr-review/issues/11), it can be possible
 https://github.com/mlarhrouch/azure-pipeline-gpt-pr-review/issues/11

**Comment by mlarhrouch** [comment]
@kanvishok the plugin is now supporting Azure OpenAI (you can use any model you want there), is this fix your issue ?

**Comment by kanvishok** [comment]
@mlarhrouch  I think azure openAI is expensive than chat gpt. can't you give the option to input the GPT model?

**Comment by mlarhrouch** [comment]
@kanvishok now the you can use gpt-4 model to review your PRs
