### ISSUE TITLE
Not Working in Azure DevOps Server 2019

### ISSUE THREAD

**Issue by sriramdasbalaji** [mlarhrouch/azure-pipeline-gpt-pr-review#9]
Hi Team,

We are trying to use this extension in Azure DevOps Server 2019. When we run the pipeline we are facing below issue

issue 1: Plugin is not detecting target branch

![image](https://github.com/mlarhrouch/azure-pipeline-gpt-pr-review/assets/13716984/0614be53-75ba-48c7-b434-98606fc17393)

Issue: Self Signed certificate issue

I tried to give Target branch through variables to check, then I am getting below error
![image](https://github.com/mlarhrouch/azure-pipeline-gpt-pr-review/assets/13716984/b9bc26a3-6577-4706-a711-721c6ffcfe9e)

Please let us know how we can make this work in On-prem Azure DevOps server 2019

Thanks
Balaji

**Comment by shailesh** [comment]
@mlarhrouch Need help.

**Comment by ezephillips** [comment]
Exactly the same in Devops Server 2020:

fatal: ambiguous argument 'origin/undefined': unknown revision or path not in the working tree. Use '--' to separate paths from revisions, like this: 'git <command> [<revision>...] -- [<file>...]'

![image](https://github.com/mlarhrouch/azure-pipeline-gpt-pr-review/assets/30844852/720d6cca-2b49-4870-bb27-7862fcd2c128)

And I Use AzureOpenAI
Thanx in advance

**Comment by mlarhrouch** [comment]
@ezephillips seems like in Devops Server there is no System.PullRequest.TargetBranchName variable, a new PR will be created to fix this

**Comment by ezephillips** [comment]
> @ezephillips seems like in Devops Server there is no System.PullRequest.TargetBranchName variable, a new PR will be created to fix this
Great! Thnx!!

**Comment by mlarhrouch** [comment]
@ezephillips a new version of the package is published (version 0.8.3), can you please check if the issue is fixed for you

**Comment by mlarhrouch** [comment]
@ezephillips notice that this repo is not supporting AzureOpenAI yet, a new issue is created to support it https://github.com/mlarhrouch/azure-pipeline-gpt-pr-review/issues/11
